# Generated by Django 3.1.5 on 2021-02-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210208_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpostcomment',
            old_name='meme',
            new_name='post',
        ),
    ]
