# Generated by Django 3.1.5 on 2021-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210309_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Кооткое описание'),
        ),
    ]
