# Generated by Django 3.1.5 on 2021-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumsubcategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
