# Generated by Django 3.1.5 on 2021-02-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210212_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название раздела')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Раздел форума',
                'verbose_name_plural': 'Разделы форума',
            },
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name': 'Категория форума', 'verbose_name_plural': 'Категории форума'},
        ),
        migrations.AlterModelOptions(
            name='forumsubcategory',
            options={'verbose_name': 'Подкатегория форума', 'verbose_name_plural': 'Подкатегории форума'},
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='forumsubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='forum.forumcategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='forum.forumsection', verbose_name='Радительский раздел'),
        ),
    ]
