# Generated by Django 3.1.5 on 2021-03-29 11:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210309_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пост на форуме', 'verbose_name_plural': 'Посты на форуме'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
