# Generated by Django 3.1.5 on 2021-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memecomment',
            name='parent',
        ),
    ]
