# Generated by Django 3.1.5 on 2021-02-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_remove_memecomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.memecomment', verbose_name='Радительский комментарий'),
        ),
    ]
