# Generated by Django 3.1.5 on 2021-02-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_memecomment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecomment',
            old_name='parent',
            new_name='parentComment',
        ),
    ]
