# Generated by Django 3.1.5 on 2021-02-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20210207_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecomment',
            old_name='parentComment',
            new_name='parent',
        ),
    ]
