# Generated by Django 3.1.5 on 2021-03-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0004_auto_20210309_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_subcategory_on_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.forumsubcategory', verbose_name='Подкатегория на главной')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
